# Generated by Django 6.0.3 on 2026-03-23 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('session', models.CharField(choices=[('m', 'May/June'), ('o', 'October/November'), ('f', 'Feb/March')], max_length=1)),
                ('variant', models.IntegerField(help_text='Paper variant: 1, 2, or 3')),
                ('question_paper_url', models.URLField(blank=True, null=True)),
                ('mark_scheme_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube video link', null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., 1.1, 2.3', max_length=10)),
                ('name', models.CharField(help_text='e.g., States of Matter', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(help_text='e.g., 1a, 2c', max_length=10)),
                ('question_text', models.TextField()),
                ('marks', models.IntegerField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('structured', 'Structured'), ('practical', 'Practical'), ('theory', 'Theory')], default='mcq', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pastpapers.pastpaper')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastpapers.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastpapers.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(help_text="For MCQ: e.g., 'B'. For structured: model answer")),
                ('explanation', models.TextField()),
                ('video_explanation_url', models.URLField(blank=True, null=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('marking_points', models.JSONField(default=list, help_text='List of marking points')),
                ('examiner_tip', models.TextField(blank=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='pastpapers.question')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='pastpapers.topic'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attempted', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('answer_given', models.TextField(blank=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastpapers.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
