# Generated by Django 6.0.3 on 2026-03-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('zoom_link', models.URLField(help_text='Zoom/Google Meet/YouTube Live link')),
                ('recording_url', models.URLField(blank=True, help_text='Recording link after class', null=True)),
                ('is_upcoming', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='pastpapers.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write notes in markdown or HTML format')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pastpapers.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='YouTube video link')),
                ('duration', models.CharField(blank=True, help_text='e.g., 15:30', max_length=20)),
                ('thumbnail', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pastpapers.subtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
